spring.application.name=ninjas

#URL de conexão com o BD
spring.datasource.url=jdbc:postgresql://localhost:5432/ninja

# usuário e senha do BD
spring.datasource.username=postgres
spring.datasource.password=123456

#driver responsável por fazer a conexão com o PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# define como o Hiberntae gerencia as tabelas (update = cria/atualiza sem apagar dados)
spring.jpa.hibernate.ddl-auto=update

# mostra no console as consultas SQL executadas / formata as consultas no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# define o tipo de banco utilizado (dialeto do POstgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect